Fix linux-pkg build of projects/auto-update/master/merging
We currently have linux-pkg update jobs failing like this:
```
...<cropped>...
dh build
   debian/rules override_dh_auto_build
make[1]: Entering directory '/export/home/delphix/linux-pkg/packages/bpftrace/tmp/repo'
mkdir obj-x86_64-linux-gnu && cd obj-x86_64-linux-gnu && \
cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=/usr ..
...<cropped>..
-- Looking for sys/sdt.h
-- Looking for sys/sdt.h - found
-- Found LLVM 7.0.0: /usr/lib/llvm-7/lib/cmake/llvm
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindGTest.cmake:196 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  tests/CMakeLists.txt:95 (find_package)

-- Configuring incomplete, errors occurred!
See also "/export/home/delphix/linux-pkg/packages/bpftrace/tmp/repo/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
See also "/export/home/delphix/linux-pkg/packages/bpftrace/tmp/repo/obj-x86_64-linux-gnu/CMakeFiles/CMakeError.log".
debian/rules:30: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/export/home/delphix/linux-pkg/packages/bpftrace/tmp/repo'
debian/rules:19: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
Error: failed command 'dpkg-buildpackage -b -us -uc'
```

Here is the linux-pkg reproducer:
```
~/linux-pkg$ ./buildpkg.sh -b refs/heads/projects/auto-update/master/merging  bpftrace
```

This failure happened because of this upstream commit:
https://github.com/delphix/bpftrace/commit/5b96243750324a9a0014aeb9f81988d9d86ce572

The above commit suggests that for older versions of
distros like Ubuntu the -DVENDOR_GTEST option is supplied
to the compiler.